### ISSUE TITLE
Why did you decide to use VGG annotations?

### ISSUE THREAD

**Issue by adsk2050** [zekeriyyaa/MaskRCNN-Modanet-Fashion-Segmentation-and-Classification#3]
As you had to take the pain to create a script to convert COCO annotations to VGG, you must have had an important reason for it. I have just started with working on your code. Would love to know the thought process behind this.

**Comment by zekeriyyaa** [comment]
You can reach the reason of it under the header : **"Generate Custom Dataset's Labels"**
After the segmentation step, it returns an object that includes mask of segmented clothes and their class ID. So, the mask here is VGG annotation type. That's why i had to convert them into COCO type.



_Our custom dataset was passing into trained model mask_rcnn_Modanet.h5 as input. As a result, we got segmentation of clothes. The segmentation result has mask of segmented clothes and their class ID. Using this mask we produced detected clothes's boundaries and their labels as vgg annotation type. This is how we can handle the issue which is already talked above as our unlabel dataset._

**Comment by adsk2050** [comment]
Thank you @zekeriyyaa  :-)
